export const heroSlides = [
  {
    id: 1,
    shadowText: "Fuel Your Startup Journey ",
    mainText: "From Idea to Impact ",
    imageUrl: "/images/girl_on_computer.png",
    link: null,
  },
  {
    id: 2,
    shadowText: "HURRY UP!",
    mainText: "Fun awaits in your\nHappy Meal",
    imageUrl: "https://mcdindia.com/wp-content/uploads/2026/02/website-banner-revised_240226.jpg",
    link: null,
  },
  {
    id: 3,
    shadowText: "The New",
    mainText: "Signature Collection\nby McDonald's",
    imageUrl: "https://mcdindia.com/wp-content/uploads/2025/12/website-banner-1-1.jpg",
    link: null,
  },
  {
    id: 4,
    shadowText: "McCafé Subscription Deal",
    mainText: "61% More savings.",
    imageUrl: "https://mcdindia.com/wp-content/uploads/2026/01/website-banner-mccafe-scaled.jpg",
    link: "#",
  },
  {
    id: 5,
    shadowText: "Breakfast Menu",
    mainText: "Start your day with\nMcDonald's Breakfast",
    imageUrl: "https://mcdindia.com/wp-content/uploads/2026/02/breakfast.jpg",
    link: null,
  },
  {
    id: 6,
    shadowText: "Happy Birthday",
    mainText: "Celebrate your child's\nbirthday with us",
    imageUrl: "https://mcdindia.com/wp-content/uploads/2022/07/img1.jpg",
    link: null,
  },
  {
    id: 7,
    shadowText: "Notice",
    mainText: "Beware of\nScams",
    imageUrl: "https://mcdindia.com/wp-content/uploads/2021/07/slide-2-new.jpg",
    link: null,
  },
];

export type MenuItem = {
  id: number;
  name: string;
  tagline: string;
  desc: string;
  serving: string;
  allergens: string;
  imageUrl: string;
  ingredients: string;
  nutrition: { label: string; value: string }[];
};

export const burgerItems: MenuItem[] = [
  {
    id: 1,
    name: "Veg Surprise Burger",
    tagline: "A surprise that will leave you wide-eyed.",
    desc: "A scrumptious potato patty topped with a delectable Italian herb sauce and shredded onions placed between perfectly toasted buns.",
    serving: "132g",
    allergens: "Cereal containing gluten, Milk, Soya",
    imageUrl: "https://mcdindia.com/wp-content/uploads/2023/01/veg-surprise-burger-1.png",
    ingredients: "Regular Bun, Italian mayo, Shredded onion, Herb Chilli Potato patty",
    nutrition: [
      { label: "Energy", value: "313.44kCal" },
      { label: "Protein", value: "5.71g" },
      { label: "Total Fat", value: "14.95g" },
      { label: "Sat Fat", value: "3.73g" },
      { label: "Trans Fat", value: "0.14g" },
      { label: "Cholesterols", value: "0.0mg" },
      { label: "Total Carbs", value: "39.84g" },
      { label: "Total Sugars", value: "5.66g" },
      { label: "Added Sugars", value: "1.64g" },
      { label: "Sodium", value: "504.19mg" },
    ],
  },
  {
    id: 2,
    name: "McAloo Tikki Burger®",
    tagline: "The one that never goes out of f(l)avour.",
    desc: "A golden fried vegetarian patty prepared with peas, potato and infused with aromatic spices. Clubbed with sliced tomatoes, shredded red onion, and tangy tomato mayonnaise. Served in a warm toasted bun.",
    serving: "146g",
    allergens: "Cereal containing gluten, Milk, Soya",
    imageUrl: "https://mcdindia.com/wp-content/uploads/2020/02/2.1-mcaloo-tikki-cheese.png",
    ingredients: "Regular bun crown, Tom-Mayo sauce, Sliced tomatoes, Shredded onion, Aloo tikki patty, Regular bun heel",
    nutrition: [
      { label: "Energy", value: "339.52kCal" },
      { label: "Protein", value: "8.50g" },
      { label: "Total Fat", value: "11.31g" },
      { label: "Sat Fat", value: "4.27g" },
      { label: "Trans Fat", value: "0.20g" },
      { label: "Cholesterols", value: "1.47mg" },
      { label: "Total Carbs", value: "50.27g" },
      { label: "Total Sugars", value: "7.05g" },
      { label: "Added Sugars", value: "4.07g" },
      { label: "Sodium", value: "545.34mg" },
    ],
  },
  {
    id: 3,
    name: "McVeggie®",
    tagline: "Pure taste. Pure veg.",
    desc: "A delectable patty made of green goodness, potatoes, peas, carrots and a selection of Indian spices. Topped with crispy lettuce, mayonnaise, and packed into sesame toasted buns.",
    serving: "168g",
    allergens: "Cereal containing gluten, Milk, Soya",
    imageUrl: "https://mcdindia.com/wp-content/uploads/2020/02/2.3-mc-veggie-single.png",
    ingredients: "Quarter bun crown, Veg mayonnaise, Shredded lettuce, Vegetable patty, Quarter bun heel",
    nutrition: [
      { label: "Energy", value: "402.05kCal" },
      { label: "Protein", value: "10.24g" },
      { label: "Total Fat", value: "13.83g" },
      { label: "Sat Fat", value: "5.34g" },
      { label: "Trans Fat", value: "0.16g" },
      { label: "Cholesterols", value: "2.49mg" },
      { label: "Total Carbs", value: "56.54g" },
      { label: "Total Sugars", value: "7.90g" },
      { label: "Added Sugars", value: "4.49g" },
      { label: "Sodium", value: "706.13mg" },
    ],
  },
  {
    id: 4,
    name: "McChicken®",
    tagline: "Familiarity breeds confidence.",
    desc: "Batter & breaded chicken patty containing green peas, carrots, green beans, onion, potatoes, rice and spices, served in a bun with eggless mayonnaise and lettuce.",
    serving: "173g",
    allergens: "Cereal containing gluten, Milk, Soya",
    imageUrl: "https://mcdindia.com/wp-content/uploads/2020/02/2.4-mcchicken-single.png",
    ingredients: "Quarter bun crown, Veg mayonnaise, Shredded lettuce, McChicken patty, Quarter bun heel",
    nutrition: [
      { label: "Energy", value: "400.80kCal" },
      { label: "Protein", value: "15.66g" },
      { label: "Total Fat", value: "15.70g" },
      { label: "Sat Fat", value: "5.47g" },
      { label: "Trans Fat", value: "0.16g" },
      { label: "Cholesterols", value: "31.17mg" },
      { label: "Total Carbs", value: "47.98g" },
      { label: "Total Sugars", value: "5.53g" },
      { label: "Added Sugars", value: "4.49g" },
      { label: "Sodium", value: "766.33mg" },
    ],
  },
  {
    id: 5,
    name: "Fillet-O-Fish®",
    tagline: "This one's a great catch.",
    desc: "Made with Alaskan Pollock sourced from sustainable fisheries; topped with a melty American cheese slice and creamy tartar sauce; and served on a soft, steamed bun.",
    serving: "136g",
    allergens: "Cereal containing gluten, Milk, Egg, Fish, Soya",
    imageUrl: "https://mcdindia.com/wp-content/uploads/2020/02/2.5-filet-o-fish.png",
    ingredients: "Steamed regular bun, Chunky tartar mayo, Fish fillet patty, Cheese",
    nutrition: [
      { label: "Energy", value: "348.11kCal" },
      { label: "Protein", value: "15.44g" },
      { label: "Total Fat", value: "14.16g" },
      { label: "Sat Fat", value: "5.79g" },
      { label: "Trans Fat", value: "0.21g" },
      { label: "Cholesterols", value: "32.83mg" },
      { label: "Total Carbs", value: "38.85g" },
      { label: "Total Sugars", value: "5.58g" },
      { label: "Added Sugars", value: "3.54g" },
      { label: "Sodium", value: "530.54mg" },
    ],
  },
  {
    id: 6,
    name: "McSpicy Paneer®",
    tagline: "Let paneer surprise you.",
    desc: "Crispy and spicy paneer patty with creamy tandoori sauce and crispy lettuce topping.",
    serving: "199g",
    allergens: "Cereal containing gluten, Milk, Soya",
    imageUrl: "https://mcdindia.com/wp-content/uploads/2020/02/2.6-mcspicy-paneer-single.png",
    ingredients: "Quarter pounder bun crown, Shredded lettuce, Tandoori mayo, Spicy paneer patty, Quarter pounder bun heel",
    nutrition: [
      { label: "Energy", value: "652.76kCal" },
      { label: "Protein", value: "20.29g" },
      { label: "Total Fat", value: "39.45g" },
      { label: "Sat Fat", value: "17.12g" },
      { label: "Trans Fat", value: "0.18g" },
      { label: "Cholesterols", value: "21.85mg" },
      { label: "Total Carbs", value: "52.33g" },
      { label: "Total Sugars", value: "8.35g" },
      { label: "Added Sugars", value: "5.27g" },
      { label: "Sodium", value: "1074.58mg" },
    ],
  },
  {
    id: 7,
    name: "McSpicy Chicken®",
    tagline: "Hot. In more ways than one.",
    desc: "Zesty and redolent whole muscle leg meat patty: Fried to perfect golden tan; quenched with creamy veg mayo and garden-fresh shredded iceberg lettuce.",
    serving: "186g",
    allergens: "Cereal containing gluten, Milk, Egg, Soya",
    imageUrl: "https://mcdindia.com/wp-content/uploads/2020/02/2.7-mc-spicy-chicken-single.png",
    ingredients: "Quarter pounder bun crown, Veg sauce, Shredded lettuce, McSpicy chicken patty, Quarter pounder bun heel",
    nutrition: [
      { label: "Energy", value: "451.92kCal" },
      { label: "Protein", value: "21.46g" },
      { label: "Total Fat", value: "19.36g" },
      { label: "Sat Fat", value: "7.63g" },
      { label: "Trans Fat", value: "0.18g" },
      { label: "Cholesterols", value: "66.04mg" },
      { label: "Total Carbs", value: "46.08g" },
      { label: "Total Sugars", value: "5.88g" },
      { label: "Added Sugars", value: "4.49g" },
      { label: "Sodium", value: "928.52mg" },
    ],
  },
  {
    id: 8,
    name: "Spicy Paneer Wrap®",
    tagline: "Unwrap deliciousness.",
    desc: "Tender paneer patty with a fiery, crunchy batter coating; dressed with fresh veggies and seasonings; topped with creamy sauce; and a dash of mustard and melted cheese.",
    serving: "250g",
    allergens: "Cereal containing gluten, Milk, Soya",
    imageUrl: "https://mcdindia.com/wp-content/uploads/2020/02/2.8-big-spicy-paneer-wrap-single.png",
    ingredients: "Whole wheat flat bread, Spicy paneer patty, Veg mayo, Lettuce, Onion, Tomato, Mustard sauce, Cheese",
    nutrition: [
      { label: "Energy", value: "674.68kCal" },
      { label: "Protein", value: "20.96g" },
      { label: "Total Fat", value: "39.10g" },
      { label: "Sat Fat", value: "19.73g" },
      { label: "Trans Fat", value: "0.26g" },
      { label: "Cholesterols", value: "40.93mg" },
      { label: "Total Carbs", value: "59.278g" },
      { label: "Total Sugars", value: "3.50g" },
      { label: "Added Sugars", value: "1.08g" },
      { label: "Sodium", value: "1087.46mg" },
    ],
  },
  {
    id: 9,
    name: "Veg Maharaja Mac®",
    tagline: "A feast fit for kings (and queens).",
    desc: "A double-decker toasted Maharaja bun sandwiched with one layer of corn & cheese patty; crunchy iceberg lettuce; shredded onion; and a slice of cheese.",
    serving: "306g",
    allergens: "Cereal containing gluten, Milk, Soya",
    imageUrl: "https://mcdindia.com/wp-content/uploads/2020/02/2.10-maharaja-mac-veg.png",
    ingredients: "Maharaja bun crown, Cocktail sauce, Shredded lettuce, Shredded onion, Jalepenos, Corn & cheese patty, Sliced cheese, Maharaja bun heel",
    nutrition: [
      { label: "Energy", value: "832.67kCal" },
      { label: "Protein", value: "24.17g" },
      { label: "Total Fat", value: "37.94g" },
      { label: "Sat Fat", value: "16.83g" },
      { label: "Trans Fat", value: "0.28g" },
      { label: "Cholesterols", value: "36.19mg" },
      { label: "Total Carbs", value: "93.84g" },
      { label: "Total Sugars", value: "11.52g" },
      { label: "Added Sugars", value: "6.92g" },
      { label: "Sodium", value: "1529.22mg" },
    ],
  },
];

export const snacksItems: MenuItem[] = [
  {
    id: 1,
    name: "Pizza McPuff®",
    tagline: "Something different. Something delicious.",
    desc: "A blend of assorted vegetables (carrot, beans, capsicum, onion & green peas); mozzarella cheese mixed with tomato sauce; and exotic spices stuffed in rectangle shaped savoury dough.",
    serving: "87g",
    allergens: "Cereal containing gluten, Milk, Soya",
    imageUrl: "https://mcdindia.com/wp-content/uploads/2020/02/3.1-pizza-mcpuff.png",
    ingredients: "Assorted vegetables, Refined wheat flour, Pizza seasoning",
    nutrition: [
      { label: "Energy", value: "228.21kCal" },
      { label: "Protein", value: "5.45g" },
      { label: "Total Fat", value: "11.44g" },
      { label: "Sat Fat", value: "5.72g" },
      { label: "Trans Fat", value: "0.09g" },
      { label: "Cholesterols", value: "5.17mg" },
      { label: "Total Carbs", value: "24.79g" },
      { label: "Total Sugars", value: "2.73g" },
      { label: "Added Sugars", value: "0.35g" },
      { label: "Sodium", value: "390.74mg" },
    ],
  },
  {
    id: 2,
    name: "Chicken McNuggets®",
    tagline: "Each bite is better than the last.",
    desc: "Bite-sized pieces of breaded, boneless chicken formed in various shapes (Ball, Boot, Bell & Bone) fried and served hot with smoky Barbeque Sauce or Mustard Sauce.",
    serving: "64g | 96g | 144g",
    allergens: "Cereal containing gluten",
    imageUrl: "https://mcdindia.com/wp-content/uploads/2020/02/3.2-6pcs-chicken-nuggets.png",
    ingredients: "Chicken bites",
    nutrition: [
      { label: "Energy", value: "169.68kCal" },
      { label: "Protein", value: "10.03g" },
      { label: "Total Fat", value: "9.544g" },
      { label: "Sat Fat", value: "4.45g" },
      { label: "Trans Fat", value: "0.06g" },
      { label: "Cholesterols", value: "24.66mg" },
      { label: "Total Carbs", value: "10.50g" },
      { label: "Total Sugars", value: "0.32g" },
      { label: "Added Sugars", value: "0.00g" },
      { label: "Sodium", value: "313.25mg" },
    ],
  },
  {
    id: 3,
    name: "World Famous Fries®",
    tagline: "The legend among legends.",
    desc: "The crisp, craveable, fan favourite: our World Famous Fries®. These epic fries are crispy and golden on the outside and fluffy on the inside.",
    serving: "77g | 109g | 154g",
    allergens: "No Allergens",
    imageUrl: "https://mcdindia.com/wp-content/uploads/2020/02/3.3-fries.png",
    ingredients: "Potato and salt",
    nutrition: [
      { label: "Energy", value: "224.59kCal" },
      { label: "Protein", value: "3.38g" },
      { label: "Total Fat", value: "10.39g" },
      { label: "Sat Fat", value: "4.97g" },
      { label: "Trans Fat", value: "0.08g" },
      { label: "Cholesterols", value: "0.77mg" },
      { label: "Total Carbs", value: "27.08g" },
      { label: "Total Sugars", value: "0.39g" },
      { label: "Added Sugars", value: "0.00g" },
      { label: "Sodium", value: "153.15mg" },
    ],
  },
];

export const dessertsItems: MenuItem[] = [
  {
    id: 1,
    name: "McFlurry (Oreo)®",
    tagline: "An Oreo lover's dream.",
    desc: "Creamy vanilla soft-serve blended with Oreo cookie pieces.",
    serving: "160g",
    allergens: "Cereal containing gluten, Milk",
    imageUrl: "https://mcdindia.com/wp-content/uploads/2020/02/4.1-mcflurry-oreo.png",
    ingredients: "Soft serve mix (100% dairy), Oreo cookies",
    nutrition: [
      { label: "Energy", value: "225kCal" },
      { label: "Protein", value: "5.0g" },
      { label: "Total Fat", value: "5.8g" },
      { label: "Sat Fat", value: "3.9g" },
      { label: "Trans Fat", value: "0.12g" },
      { label: "Cholesterols", value: "16.4mg" },
      { label: "Total Carbs", value: "38g" },
      { label: "Total Sugars", value: "27g" },
      { label: "Added Sugars", value: "19g" },
      { label: "Sodium", value: "142mg" },
    ],
  },
  {
    id: 2,
    name: "Soft Serve Cone®",
    tagline: "Simple and simply delicious.",
    desc: "Creamy vanilla soft-serve ice cream swirled in a crispy cone.",
    serving: "90g",
    allergens: "Milk",
    imageUrl: "https://mcdindia.com/wp-content/uploads/2020/02/4.3-soft-serve-cone.png",
    ingredients: "Soft serve mix (100% dairy), Cone",
    nutrition: [
      { label: "Energy", value: "113kCal" },
      { label: "Protein", value: "2.8g" },
      { label: "Total Fat", value: "2.7g" },
      { label: "Sat Fat", value: "1.8g" },
      { label: "Trans Fat", value: "0.08g" },
      { label: "Cholesterols", value: "8.3mg" },
      { label: "Total Carbs", value: "19.5g" },
      { label: "Total Sugars", value: "14g" },
      { label: "Added Sugars", value: "9g" },
      { label: "Sodium", value: "65mg" },
    ],
  },
  {
    id: 3,
    name: "Sundae (Chocolate)®",
    tagline: "Heaven in every spoonful.",
    desc: "Creamy vanilla soft-serve with rich hot fudge chocolate topping.",
    serving: "94g | 137g",
    allergens: "Milk",
    imageUrl: "https://mcdindia.com/wp-content/uploads/2020/02/4.5-sundae-chocolate.png",
    ingredients: "Soft serve mix (100% dairy), Hot fudge topping",
    nutrition: [
      { label: "Energy", value: "148kCal" },
      { label: "Protein", value: "2.8g" },
      { label: "Total Fat", value: "3.4g" },
      { label: "Sat Fat", value: "2.3g" },
      { label: "Trans Fat", value: "0.09g" },
      { label: "Cholesterols", value: "9.5mg" },
      { label: "Total Carbs", value: "27g" },
      { label: "Total Sugars", value: "22g" },
      { label: "Added Sugars", value: "15g" },
      { label: "Sodium", value: "78mg" },
    ],
  },
];

export const beveragesItems: MenuItem[] = [
  {
    id: 1,
    name: "Black Coffee®",
    tagline: "Perfectly brewed for any time of the day.",
    desc: "Perfectly brewed for any time of the day.",
    serving: "200ml",
    allergens: "No Allergens",
    imageUrl: "https://mcdindia.com/wp-content/uploads/2020/03/5.1-coffee-large-1.png",
    ingredients: "Coffee",
    nutrition: [
      { label: "Energy", value: "6.80kCal" },
      { label: "Protein", value: "0.00g" },
      { label: "Total Fat", value: "0.00g" },
      { label: "Sat Fat", value: "0.00g" },
      { label: "Trans Fat", value: "0.00g" },
      { label: "Cholesterols", value: "0.00mg" },
      { label: "Total Carbs", value: "1.70g" },
      { label: "Total Sugars", value: "0.00g" },
      { label: "Added Sugars", value: "0.00g" },
      { label: "Sodium", value: "0.00mg" },
    ],
  },
  {
    id: 2,
    name: "Cold Coffee®",
    tagline: "A rich smooth creamy cold coffee.",
    desc: "A rich smooth creamy cold coffee made with coffee powder and milk.",
    serving: "250ml",
    allergens: "Milk",
    imageUrl: "https://mcdindia.com/wp-content/uploads/2022/01/cold-coffee.png",
    ingredients: "Coffee, Milk",
    nutrition: [
      { label: "Energy", value: "301.10kCal" },
      { label: "Protein", value: "9.75g" },
      { label: "Total Fat", value: "11.15g" },
      { label: "Sat Fat", value: "7.45g" },
      { label: "Trans Fat", value: "0.00g" },
      { label: "Cholesterols", value: "27.40mg" },
      { label: "Total Carbs", value: "40.20g" },
      { label: "Total Sugars", value: "37.50g" },
      { label: "Added Sugars", value: "21.25g" },
      { label: "Sodium", value: "175.00mg" },
    ],
  },
  {
    id: 3,
    name: "Iced Tea®",
    tagline: "A blend of aromatic tea and lemon.",
    desc: "A blend of aromatic tea and the fruity flavour of lemon.",
    serving: "400ml",
    allergens: "No Allergens",
    imageUrl: "https://mcdindia.com/wp-content/uploads/2020/02/5.5-iced-tea.png",
    ingredients: "Tea, Lemon",
    nutrition: [
      { label: "Energy", value: "242.52kCal" },
      { label: "Protein", value: "1.08g" },
      { label: "Total Fat", value: "0.12g" },
      { label: "Sat Fat", value: "0.00g" },
      { label: "Trans Fat", value: "0.00g" },
      { label: "Cholesterols", value: "0.00mg" },
      { label: "Total Carbs", value: "59.28g" },
      { label: "Total Sugars", value: "58.08g" },
      { label: "Added Sugars", value: "55.16g" },
      { label: "Sodium", value: "16.68mg" },
    ],
  },
  {
    id: 4,
    name: "Masala Chai®",
    tagline: "A smooth and spicy blend.",
    desc: "Masala chai is a smooth and spicy blend of natural tea extract, milk solids, black pepper, fennel, clove and cinnamon.",
    serving: "90ml | 150ml",
    allergens: "Milk",
    imageUrl: "https://mcdindia.com/wp-content/uploads/2022/01/tea.png",
    ingredients: "Tea, Milk, Spices",
    nutrition: [
      { label: "Energy", value: "54.97kCal" },
      { label: "Protein", value: "0.80g" },
      { label: "Total Fat", value: "0.85g" },
      { label: "Sat Fat", value: "0.51g" },
      { label: "Trans Fat", value: "0.02g" },
      { label: "Cholesterols", value: "0.00mg" },
      { label: "Total Carbs", value: "11.02g" },
      { label: "Total Sugars", value: "8.79g" },
      { label: "Added Sugars", value: "7.98g" },
      { label: "Sodium", value: "4.13mg" },
    ],
  },
];

export type Store = {
  id: number;
  city: string;
  address: string;
  dineIn: "Open" | "Closed";
  delivery: "Open" | "Closed";
  phone: string;
  mapsUrl: string;
  types: string[];
};

export const stores: Store[] = [
  { id: 1, city: "Guwahati", address: "McDonald's Family Restaurant, Ground floor, Beekay Tower, Ganesh Guri", dineIn: "Open", delivery: "Open", phone: "8130816668", mapsUrl: "https://maps.app.goo.gl/TPVG1L9ReQaki6Uk6", types: ["Delivery", "Birthday", "McCafe"] },
  { id: 2, city: "Guwahati", address: "558, Newslive Building, GS Road, Christian Basti, Dispur", dineIn: "Open", delivery: "Open", phone: "8448439711", mapsUrl: "https://maps.app.goo.gl/TPVG1L9ReQaki6Uk6", types: ["Delivery", "Birthday", "McCafe"] },
  { id: 3, city: "Muzaffarpur", address: "Shop No- G01 to G06 Ground Floor, Dwarika City Centre (DCC), Opposite MPS Science College, NH-28", dineIn: "Open", delivery: "Open", phone: "9870103007", mapsUrl: "https://maps.app.goo.gl/ktdbsaQR9A99NAB26", types: ["Delivery"] },
  { id: 4, city: "Patna", address: "Ground Floor, Elphinston Cinema, Village, Moharampura, Gandhi Maidan East", dineIn: "Open", delivery: "Open", phone: "8800722571", mapsUrl: "https://goo.gl/maps/BDquziZf4eMXurGv8", types: ["Kiosk", "Delivery", "Birthday", "McCafe"] },
  { id: 5, city: "Patna", address: "Furniture Mall, Ground Floor, Plot No.-3, Near RPS More, Bailly Road, Saguna More, Danapur", dineIn: "Open", delivery: "Open", phone: "8448431722", mapsUrl: "https://maps.app.goo.gl/otPSQXiD1ZLhpLok9", types: ["Delivery", "McCafe"] },
  { id: 6, city: "Chandigarh", address: "Plot No.1, Hotel Aroma Complex. 1st Floor. Sector- 22C, Chandigarh- 160022", dineIn: "Open", delivery: "Open", phone: "8283808158", mapsUrl: "https://goo.gl/maps/88QXh6tjwvXGtyvG7", types: ["Kiosk", "Delivery", "Birthday", "McCafe"] },
  { id: 7, city: "Chandigarh", address: "Elante Mall, Plot No. 178-178A. Industrial & Business Park. Phase-1", dineIn: "Open", delivery: "Open", phone: "9876896969", mapsUrl: "https://goo.gl/maps/gjA4H6wD9Qam1NGRA", types: [] },
  { id: 8, city: "Chandigarh", address: "Fun Republic, Dhillon Complex, Manimarja, Chandigarh- 160101", dineIn: "Open", delivery: "Open", phone: "9878622219", mapsUrl: "https://goo.gl/maps/hHdTZzhTQjbXkXV17", types: ["Delivery", "Birthday"] },
  { id: 9, city: "Chandigarh", address: "SCO 457-458, Sector-35 C, Chandigarh-160035", dineIn: "Open", delivery: "Open", phone: "9878622299", mapsUrl: "https://goo.gl/maps/Axqtv72ANJhfEX648", types: ["Delivery", "Birthday", "McCafe"] },
  { id: 10, city: "New Delhi", address: "0276 DELHI T 2 ROAD CARGO COMPLEX GF-1, PUBLIC AMENITIES COMPLEX, HUB CARGO GATE NO 5, DELHI CARGO AIRPORT", dineIn: "Open", delivery: "Open", phone: "9667569544", mapsUrl: "https://maps.app.goo.gl/3mVU4G2Cei9GmQqK6", types: ["Drive-Thru", "Delivery"] },
  { id: 11, city: "Delhi", address: "T-310. Ambience Mall, Plot No-2, Shopping Complex Phase-II, Nebon Mandela Road, Vasant Kunj", dineIn: "Open", delivery: "Closed", phone: "9711958884", mapsUrl: "https://maps.app.goo.gl/oqHZBHUwyMqiKPgT9", types: ["Delivery", "McCafe"] },
  { id: 12, city: "Delhi", address: "BG-02, HUDCO Place, Ansal Plaza Khel Gaon Road New Delhi- 110049", dineIn: "Open", delivery: "Open", phone: "9711882104", mapsUrl: "https://goo.gl/maps/adpsw39W5jvSUKVN9", types: ["Kiosk", "Delivery", "Birthday"] },
  { id: 13, city: "Delhi", address: "47, Basant Lok, Community Centre, Vasant Vihar, New Delhi-110057", dineIn: "Open", delivery: "Open", phone: "9899795811", mapsUrl: "https://goo.gl/maps/QBWwF3jEDFjussUH6", types: ["Breakfast", "Delivery", "McCafe"] },
  { id: 14, city: "Delhi", address: "Plot No. 9B & C, Cross River Mall, CBD Shahdara. Delhi- 110032", dineIn: "Open", delivery: "Open", phone: "9811852820", mapsUrl: "https://goo.gl/maps/oFJDHkBgdNE7w1vR8", types: ["Drive-Thru", "Delivery", "Birthday"] },
  { id: 15, city: "New Delhi", address: "N-10 Connaught Place", dineIn: "Open", delivery: "Open", phone: "8588839324", mapsUrl: "https://goo.gl/maps/BoWVPaxm7RWzWxsz9", types: ["Delivery"] },
  { id: 16, city: "New Delhi", address: "Commercial Complex-II /1888-89, Kumar Theatre, Chandni Chowk, New Delhi-110006", dineIn: "Open", delivery: "Open", phone: "9711882126", mapsUrl: "https://goo.gl/maps/ENLhHe3kUVQD9qkJ8", types: ["Kiosk", "Delivery"] },
];
